name: test-latest-release-public-out

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test download asset
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download asset action step
      uses: fabriciobastian/download-release-asset-action@v1.0.5
      with:
        version: latest
        repository: JsonRpcNet/JsonRpcNet.Ui
        file: jsonrpcnet-ui.zip
        out: ./some/deep/path/
    - name: Unzip output file
      run: unzip ./some/deep/path/jsonrpcnet-ui.zip
